import { coerceToBase64Url } from "../common/utils.js";
import { coerceToBase64 } from "../common/utils.js";
export function checkRpId(rpId: any): string;
import { ab2str } from "../common/utils.js";
import { coerceToArrayBuffer } from "../common/utils.js";
import { abToBuf } from "../common/utils.js";
import { randomValues } from "../common/utils.js";
import { isBase64Url } from "../common/utils.js";
export function checkOrigin(str: any): any;
import { abEqual } from "../common/utils.js";
import { isPem } from "../common/utils.js";
import { isPositiveInteger } from "../common/utils.js";
import { hashDigest } from "../common/utils.js";
export function verifySignature(publicKey: any, expectedSignature: any, data: any): Promise<any>;
import { appendBuffer } from "../common/utils.js";
import { base64 } from "../common/utils.js";
export function jwkToPem(jwk: any): Promise<any>;
export { coerceToBase64Url, coerceToBase64, ab2str, coerceToArrayBuffer, abToBuf, randomValues, isBase64Url, abEqual, isPem, isPositiveInteger, hashDigest, appendBuffer, base64 };
