export function checkDomainOrUrl(value: any, name: any, rules?: {}): string;
export function checkOrigin(str: any): any;
export function checkRpId(rpId: any): string;
export function checkUrl(value: any, name: any, rules?: {}): string;
export function getEmbeddedJwk(jwsHeader: any, alg: any): Promise<any>;
export function getHostname(urlIn: any): any;
export function hashDigest(o: any, alg: any): Promise<any>;
export function randomValues(n: any): Uint8Array;
export function verifySignature(publicKeyPem: any, expectedSignature: any, data: any, hashName: any): Promise<any>;
export const webcrypto: any;
export { cbor, decodeProtectedHeader, exportSPKI, fromBER, importJWK, importSPKI, jwtVerify, pkijs };
